[build]
  publish = "dist"
	functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat/index.js"
  status = 200

[[redirects]]
 from = "/hired/game/*"
 to = "/hired/game/[id]/index.html"
 status = 200

[[redirects]]
 from = "/hired/join/*"
 to = "/hired/join/[id]/index.html"
 status = 200

#[[redirects]]
#  from = "/hired/*"
#  to = "http://localhost:3000/hired/:splat"
#  status = 200
#	force = true

[[redirects]]
  from = "/"
  to = "/hired/"
