[build]
  publish = "dist"
	functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat/index.js"
  status = 200

[[redirects]]
  from = "/hired/*"
  to = "/hired/index.html"
  status = 200

#[[redirects]]
#  from = "/hired/*"
#  to = "http://localhost:3000/hired/:splat"
#  status = 200
#	force = true

[[redirects]]
  from = "/"
  to = "/hired/"
