ConnectionsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: connections
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
    AttributeDefinitions:
      - AttributeName: connectionId
        AttributeType: S
    KeySchema:
      - AttributeName: connectionId
        KeyType: HASH
    SSESpecification:
      SSEEnabled: true
    TimeToLiveSpecification:
      AttributeName: ttl
      Enabled: true
RoomsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: rooms
    AttributeDefinitions:
      - AttributeName: room
        AttributeType: S
    KeySchema:
      - AttributeName: room
        KeyType: HASH
    SSESpecification:
      SSEEnabled: true
    TimeToLiveSpecification:
      AttributeName: ttl
      Enabled: true
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
    StreamSpecification:
      StreamViewType: NEW_IMAGE
