ConnectionsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: connections
    AttributeDefinitions:
      - AttributeName: connectionId
        AttributeType: S
    BillingMode: PAY_PER_REQUEST
    KeySchema:
      - AttributeName: connectionId
        KeyType: HASH
    SSESpecification:
      SSEEnabled: true
    TimeToLiveSpecification:
      AttributeName: ttl
      Enabled: true
RoomsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: rooms
    AttributeDefinitions:
      - AttributeName: room
        AttributeType: S
    BillingMode: PAY_PER_REQUEST
    KeySchema:
      - AttributeName: room
        KeyType: HASH
    SSESpecification:
      SSEEnabled: true
    TimeToLiveSpecification:
      AttributeName: ttl
      Enabled: true
